config/routes.rb
Rails.application.routes.draw do

  get '/auth/github/callback', to: 'sessions#create'
  get '/logout',               to: 'sessions#logout'

  put '/milestones/sort'   => 'milestones#update_sort_order'
  put '/milestones/:title' => 'milestones#update', title: /.+/

  put '/issues/sort'       => 'issues#update_sort_order'
  put '/issues/:id'        => 'issues#update'
  post '/issues'           => 'issues#create'
  
  get '/milestones/:title'       => 'boards#milestone', as: 'show_milestone', title: /[^\/]+/
  get '/milestones/:title/:view' => 'boards#milestone', as: 'show_milestone_view', title: /[^\/]+/

  get '/boards' => 'boards#show'

  get '/your-issues' => 'boards#redirect_to_user'
  get '/~:login/history' => 'boards#user_history', login: /.+/
  get '/~:login/log' => 'boards#user_commits', login: /.+/
  get '/~:login' => 'boards#user', login: /.+/

  get '/' => 'boards#list_milestones'
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def show
    @milestones = Issue.distinct(:milestone)
    @issues_by_milestone = Issue.all.group_by(&:milestone)

    @contributors = Contributor.all
    @issues_by_milestone['Backlog'] = @issues_by_milestone[nil]
    @milestones << 'Backlog'
  end

  def user
    @contributor        = Contributor.find_by(login: params[:login])
    @title              = "@#{@contributor.login}'s Issues"
    @issues = Issue.where(assignee: params[:login]).open.all
    @active_milestones = Milestone.active.map(&:title) & @issues.map(&:milestone)
    @backlog_issues = []
  end

  def user_commits
    params[:days] ||= 7
    @contributor     = Contributor.find_by(login: params[:login])
    @title           = "@#{@contributor.login}'s Commits"
    @commits_by_date = Commit.where(author: params[:login]).gte(committed_at: params[:days].to_i.days.ago).desc(:committed_at).all.group_by { |c| c.committed_at.to_date }
    @commit_dates    = @commits_by_date.keys.sort.reverse
  end

  def user_history
    params[:days] ||= 7
    @contributor      = Contributor.find_by(login: params[:login])
    @title            = "@#{@contributor.login}'s History"
    @issues           = Issue.where(assignee: params[:login], state: 'closed').gte(closed_at: params[:days].to_i.days.ago).desc(:closed_at, :updated_at)
  end

  def redirect_to_user
    redirect_to "/~#{session[:github_login]}"
  end

  def milestone
    @title            = params[:title]
    @milestone        = Milestone.find_by(title: params[:title])
    @issues           = Issue.where(milestone: params[:title], state: 'open').all.to_a
    @issues           += Issue.closed_today.where(milestone: params[:title]).all.to_a
    @recently_closed_issues = @milestone.issues.closed_today.desc(:closed_at)
    @recent_commits   = @milestone.commits.today.desc(:committed_at)
    @other_commits    = @milestone.commits.not_associated_to_issue.today.all

    render template: params[:view] == 'completed' ? 'boards/milestone_completed' : 'boards/milestone_todo'
  end

  def list_milestones
    @title = "All Milestones"
    @milestones = Milestone.open.all
  end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_milestone_view_nav.html.erb
<div class="item-select" style="max-width: 800px; margin: 0 auto;">
  <a href="<%= show_milestone_view_path(@milestone.title, :todo) %>" class="<%= 'active' if params[:view] == 'todo' || params[:view].blank? %>">TODO</a>
  <a href="<%= show_milestone_view_path(@milestone.title, :completed) %>" class="<%= 'active' if params[:view] == 'completed' %>">Completed</a>
</div>

app/views/boards/list_milestones.erb
<% if @milestones.active.present? %>
  <div class="grouping">
    <h3>Active</h3>

    <div class="milestones">
      <% @milestones.active.each do |milestone| %>
        <div class="milestone" data-object-id="<%= milestone._id %>" data-entity-type="milestone">
          <div class="content">
            <div class="title"><%= link_to milestone.title, "/milestones/#{milestone.title}" %></div>
            <div class="repo-list">
              <% milestone.repos.each do |repo| %>
                <div class="repo"><a href="https://github.com/<%= ENV['DEFAULT_GITHUB_ORG'] %>/<%= repo %>/milestones" target="_blank"><%= repo %></a></div>
              <% end %>
              <div style="clear: both;"></div>
            </div>
          </div>
          <div class="actions">
            <span class="primary-actions">
              <i class="action material-icons waves-effect waves-red" data-status="inactive">pause</i>
              <i class="action material-icons waves-effect waves-green" data-status="closed">stop</i>
            </span>
          </div>
          <div style="clear: both;"></div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>


<% if @milestones.inactive.present? %>
  <div class="grouping">
    <h3>Backlog</h3>

    <div class="milestones">
      <% @milestones.inactive.each do |milestone| %>
        <div class="milestone" data-object-id="<%= milestone._id %>" data-entity-type="milestone">
          <div class="content">
            <div class="title"><%= link_to milestone.title, "/milestones/#{milestone.title}" %></div>
            <div class="repo-list">
              <% milestone.repos.each do |repo| %>
                <div class="repo"><a href="https://github.com/<%= ENV['DEFAULT_GITHUB_ORG'] %>/<%= repo %>/milestones" target="_blank"><%= repo %></a></div>
              <% end %>
              <div style="clear: both;"></div>
            </div>
          </div>
          <div class="actions">
            <span class="primary-actions">
              <i class="action material-icons waves-effect waves-green" data-status="active">play_arrow</i>
            </span>
          </div>
          <div style="clear: both;"></div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/boards/milestone.html.erb
<% if @recently_closed_issues.present? || @recent_commits.present? %>
  <a class="completed-work-toggle" href="#">
    <% if @recently_closed_issues.present? %>
      <%= pluralize @recently_closed_issues.length, 'issue' %> closed today<%= ',' if @recent_commits.present? %>
    <% end %>
    <%= pluralize @recent_commits.length, 'commit' if @recent_commits.present? %> &raquo;
  </a>
<% end %>

<div style="clear: both;"></div>

<div id="issues-closed-grouping" class="grouping">
  <h3>Closed Today</h3>
  <div id="issues-closed-today" class="issues not-sortable"></div>
</div>

<% if @other_commits.present? %>
  <div id="other-commits-grouping" class="grouping">
    <h3>Other Commits</h3>
    <div id="other-commits" class="commits">
      <% @other_commits.each do |commit| %>
        <div class="commit">
          <div class="author"><div class="avatar contributor-<%= commit.author %>" style="display: inline-block; height: 15px; "></div><%= commit.author %></div>
          <div class="title"><a href="<%= commit.url %>" target="_blank"><%= commit.message %></a></div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="grouping">
  <h3>In Progress</h3>
  <div id="in-progress-issues" class="issues not-sortable"></div>
</div>

<div class="grouping">
  <h3>Priority</h3>
  <div id="priority-issues" class="issues"></div>
</div>

<div class="grouping">
  <h3>TODO <a class="add-issue-trigger" href="#">+</a></h3>
  <div id="todo-list" class="issues"></div>
</div>


<script>
 $('.container').addClass('hide-completed-work');

 window.issuesCollection       = new IssuesCollection(<%= @issues.map(&:to_broadcast_h).to_json.html_safe %>);
 issuesCollection.masterFilter = function(issue) { console.log(issue.state, issue.milestone); return issue.milestone == <%= params[:title].to_json.html_safe %>; }

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.state == 'closed'; },
  target_el: '#issues-closed-today',
  template_name: 'issue',
  template_opts: {
    showCommits: true
  }
 });

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.in_progress == true && issue.state == 'open' },
  target_el: '#in-progress-issues',
  template_name: 'issue',
  template_opts: {
    showCommits: true,
    actions: ['pause','complete','avatar-reassign']
  }
 });

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.in_progress == false && issue.priority == true && issue.state == 'open' },
  target_el: '#priority-issues',
  template_name: 'issue',
  template_opts: {
    actions: ['start','avatar-reassign']
  }
 });

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.in_progress == false && issue.priority == false && issue.state == 'open' },
  target_el: '#todo-list',
  template_name: 'issue',
  template_opts: {
    actions: ['start','avatar-reassign']
  }
 });

 issuesCollection.triggerUpdate();

</script>

<%= render partial: 'components/reassign_modal' %>
<%= render partial: 'components/add_issue_modal' %>

app/views/boards/milestone_completed.html.erb
<%= render partial: 'milestone_view_nav' %>


<div id="issues-closed-grouping" class="grouping">
  <h3>Closed Today</h3>
  <div id="issues-closed-today" class="issues not-sortable"></div>
</div>

<% if @other_commits.present? %>
  <div id="other-commits-grouping" class="grouping">
    <h3>Other Commits</h3>
    <div id="other-commits" class="commits">
      <% @other_commits.each do |commit| %>
        <div class="commit">
          <div class="author"><div class="avatar contributor-<%= commit.author %>" style="display: inline-block; height: 15px; "></div><%= commit.author %></div>
          <div class="title"><a href="<%= commit.url %>" target="_blank"><%= commit.message %></a></div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="grouping">
  <h3>In Progress</h3>
  <div id="in-progress-issues" class="issues not-sortable"></div>
</div>

<div class="grouping">
  <h3>For Review</h3>
  <div id="issues-for-review" class="issues not-sortable"></div>
</div>

<script>
 window.issuesCollection       = new IssuesCollection(<%= @issues.map(&:to_broadcast_h).to_json.html_safe %>);
 issuesCollection.masterFilter = function(issue) { console.log(issue.state, issue.milestone); return issue.milestone == <%= params[:title].to_json.html_safe %>; }

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.state == 'closed'; },
  target_el: '#issues-closed-today',
  template_name: 'issue',
  template_opts: {
    showCommits: true
  }
 });

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.in_progress == true && issue.state == 'open' },
  target_el: '#in-progress-issues',
  template_name: 'issue',
  template_opts: {
    showCommits: true,
    actions: ['pause','complete','avatar-reassign']
  }
 });

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.for_review == true },
  target_el: '#issues-for-review',
  template_name: 'issue',
  template_opts: {
    showCommits: true
    // actions: ['pause','complete','avatar-reassign']
  }
 });

 issuesCollection.triggerUpdate();

</script>

<%= render partial: 'components/reassign_modal' %>
<%= render partial: 'components/add_issue_modal' %>

app/views/boards/milestone_todo.html.erb
<%= render partial: 'milestone_view_nav' %>

<div class="grouping">
  <h3>In Progress</h3>
  <div id="in-progress-issues" class="issues not-sortable"></div>
</div>

<div class="grouping">
  <h3>Priority</h3>
  <div id="priority-issues" class="issues"></div>
</div>

<div class="grouping">
  <h3>TODO <a class="add-issue-trigger" href="#">+</a></h3>
  <div id="todo-list" class="issues"></div>
</div>

<script>
 $('.container').addClass('hide-completed-work');

 window.issuesCollection       = new IssuesCollection(<%= @issues.map(&:to_broadcast_h).to_json.html_safe %>);
 issuesCollection.masterFilter = function(issue) { console.log(issue.state, issue.milestone); return issue.milestone == <%= params[:title].to_json.html_safe %>; }

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.in_progress == true && issue.state == 'open' },
  target_el: '#in-progress-issues',
  template_name: 'issue',
  template_opts: {
    showCommits: true,
    actions: ['pause','complete','avatar-reassign']
  }
 });

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.in_progress == false && issue.priority == true && issue.state == 'open' },
  target_el: '#priority-issues',
  template_name: 'issue',
  template_opts: {
    actions: ['start','avatar-reassign']
  }
 });

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.in_progress == false && issue.priority == false && issue.state == 'open' },
  target_el: '#todo-list',
  template_name: 'issue',
  template_opts: {
    actions: ['start','avatar-reassign']
  }
 });

 issuesCollection.triggerUpdate();

</script>

<%= render partial: 'components/reassign_modal' %>
<%= render partial: 'components/add_issue_modal' %>

app/views/boards/show.html.erb
<div class="grouping-container" style="width: <%= @milestones.length * 580 %>px;">
  <% @milestones.each do |milestone| %>
    <div class="grouping">
      <h3><%= milestone %></h3>

      <div class="issues">
        <% @issues_by_milestone[milestone].each do |issue| %>
          <div class="issue">
            <h6><%= issue[:title] %></h6>
            <div class="assignment contributor-<%= issue.assignee %> avatar"></div>
            <div style="clear: both;"></div>
          </div>
        <% end %>
      </div>

    </div>
  <% end %>
</div>

<div class="assignment-modal">
  <h4>Assign to</h4>

  <div class="main-contributors">
    <% @contributors.each do |c| %>
      <div class="contributor">
        <div class="avatar contributor-<%= c.login %>"></div>
        <div class="name"><%= c.login %></div>
      </div>
    <% end %>
  </div>

</div>

app/views/boards/user.html.erb
<div class="grouping">
  <h3>In Progress</h3>
  <div id="in-progress-issues" class="issues"></div>
</div>

<div class="grouping">
  <h3>High Priority</h3>
  <div id="priority-issues" class="issues"></div>
</div>

<% if @active_milestones.present? %>
  <div class="grouping">
    <h3>TODO</h3>

    <% @active_milestones.each do |milestone| %>
      <h5><%= link_to milestone, show_milestone_path(milestone) %></h5>
      <div id="milestone-issues-<%= slugify(milestone) %>" class="issues"></div>
    <% end %>
  </div>
<% end %>

<div class="grouping">
  <h3>Backlog</h3>
  <div id="backlog-issues" class="issues"></div>
</div>

<script>
 window.issuesCollection       = new IssuesCollection(<%= @issues.map(&:to_broadcast_h).to_json.html_safe %>);
 issuesCollection.masterFilter = function(issue) { return issue.assignee == <%= params[:login].to_json.html_safe %>; }

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.in_progress == true },
  target_el: '#in-progress-issues',
  template_name: 'issue',
  template_opts: {
    actions: ['pause','complete']
  }
 });

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.in_progress == false && issue.priority == true },
  target_el: '#priority-issues',
  template_name: 'issue',
  template_opts: {
    actions: ['start']
  }
 });

 <% @active_milestones.each do |milestone| %>
  issuesCollection.registerRenderer({
    filter: function(issue) { return issue.in_progress == false && issue.milestone == <%= milestone.to_json.html_safe %> },
    target_el: '#milestone-issues-<%= slugify(milestone) %>',
    template_name: 'issue',
    template_opts: {
      actions: ['start']
    }
   }); 
 <% end %> 

 issuesCollection.registerRenderer({
  filter: function(issue) { return issue.in_progress == false && issue.priority == false && !_.contains(<%= @active_milestones.to_json.html_safe %>, issue.milestone); },
  target_el: '#backlog-issues',
  template_name: 'issue',
  template_opts: {
    actions: ['start']
  }
 });


 issuesCollection.triggerUpdate();
</script>


<style>
<% Contributor.all.each do |c| %>
  .avatar.contributor-<%= c.login %> { background-image: url(<%= c.avatar_url %>); }
<% end %>
</style>

app/views/boards/user_commits.html.erb
<div id="user-log" class="grouping">
  <table class="completed-work" style="display: block;">

    <% @commit_dates.each do |date| %>
      <tr>
        <td colspan="2"><h3><%= date.strftime("%B %d") %></h3></td>
      </tr>
      <% @commits_by_date[date].each do |commit| %>
        <tr class="commit">
          <td class="repo" style="padding-right: 20px; text-align: right;"><%= commit.repo_name.gsub(/-/, '&#8209;').html_safe %></td>
          <td class="title"><a href="<%= commit.url %>" target="_blank"><%= commit.message %></a></td>
        </tr>
      <% end %>
    <% end %>

  </table>
</div>

app/views/boards/user_history.html.erb
<div class="grouping">
  <h3>Issues Closed Last <%= params[:days] %> days</h3>
  <div id="issues" class="issues"></div>
</div>

<script>
 window.issuesCollection       = new IssuesCollection(<%= @issues.map(&:to_broadcast_h).to_json.html_safe %>);
 issuesCollection.masterFilter = function(issue) { return issue.assignee == <%= params[:login].to_json.html_safe %> && issue.state == 'closed' ; }

 issuesCollection.registerRenderer({
  target_el: '#issues',
  template_name: 'issue',
  template_opts: {
    showCommits: true
  }
 });

 issuesCollection.triggerUpdate();
</script>


<style>
<% Contributor.all.each do |c| %>
  .avatar.contributor-<%= c.login %> { background-image: url(<%= c.avatar_url %>); }
<% end %>
</style>